/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntryRouteImport } from './routes/$entry'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MeRouteImport } from './routes/me'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as ObsidianRouteImport } from './routes/obsidian'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as WriteRouteImport } from './routes/write'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as TagsTagRouteImport } from './routes/tags.$tag'
import { Route as TopicsTopicRouteImport } from './routes/topics.$topic'
import { Route as WriteIdRouteImport } from './routes/write.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/$entry',
  path: '/$entry',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsidianRoute = ObsidianRouteImport.update({
  id: '/obsidian',
  path: '/obsidian',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => TagsRoute,
} as any)
const TopicsTopicRoute = TopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIdRoute = WriteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WriteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$entry': typeof EntryRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/categories': typeof CategoriesRoute
  '/console': typeof ConsoleRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/moments': typeof MomentsRoute
  '/obsidian': typeof ObsidianRoute
  '/photos': typeof PhotosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRouteWithChildren
  '/themes': typeof ThemesRoute
  '/write': typeof WriteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/write/$id': typeof WriteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$entry': typeof EntryRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/categories': typeof CategoriesRoute
  '/console': typeof ConsoleRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/moments': typeof MomentsRoute
  '/obsidian': typeof ObsidianRoute
  '/photos': typeof PhotosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRouteWithChildren
  '/themes': typeof ThemesRoute
  '/write': typeof WriteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/write/$id': typeof WriteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$entry': typeof EntryRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/categories': typeof CategoriesRoute
  '/console': typeof ConsoleRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/moments': typeof MomentsRoute
  '/obsidian': typeof ObsidianRoute
  '/photos': typeof PhotosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRouteWithChildren
  '/themes': typeof ThemesRoute
  '/write': typeof WriteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/write/$id': typeof WriteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$entry'
    | '/about'
    | '/archive'
    | '/categories'
    | '/console'
    | '/links'
    | '/login'
    | '/mcp'
    | '/me'
    | '/membership'
    | '/moments'
    | '/obsidian'
    | '/photos'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/tags'
    | '/themes'
    | '/write'
    | '/api/$'
    | '/posts/$slug'
    | '/tags/$tag'
    | '/topics/$topic'
    | '/write/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$entry'
    | '/about'
    | '/archive'
    | '/categories'
    | '/console'
    | '/links'
    | '/login'
    | '/mcp'
    | '/me'
    | '/membership'
    | '/moments'
    | '/obsidian'
    | '/photos'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/tags'
    | '/themes'
    | '/write'
    | '/api/$'
    | '/posts/$slug'
    | '/tags/$tag'
    | '/topics/$topic'
    | '/write/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$entry'
    | '/about'
    | '/archive'
    | '/categories'
    | '/console'
    | '/links'
    | '/login'
    | '/mcp'
    | '/me'
    | '/membership'
    | '/moments'
    | '/obsidian'
    | '/photos'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/tags'
    | '/themes'
    | '/write'
    | '/api/$'
    | '/posts/$slug'
    | '/tags/$tag'
    | '/topics/$topic'
    | '/write/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntryRoute: typeof EntryRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  CategoriesRoute: typeof CategoriesRoute
  ConsoleRoute: typeof ConsoleRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  MeRoute: typeof MeRoute
  MembershipRoute: typeof MembershipRoute
  MomentsRoute: typeof MomentsRoute
  ObsidianRoute: typeof ObsidianRoute
  PhotosRoute: typeof PhotosRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TagsRoute: typeof TagsRouteWithChildren
  ThemesRoute: typeof ThemesRoute
  WriteRoute: typeof WriteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  PostsSlugRoute: typeof PostsSlugRoute
  TopicsTopicRoute: typeof TopicsTopicRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$entry': {
      id: '/$entry'
      path: '/$entry'
      fullPath: '/$entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obsidian': {
      id: '/obsidian'
      path: '/obsidian'
      fullPath: '/obsidian'
      preLoaderRoute: typeof ObsidianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof TagsRoute
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/$id': {
      id: '/write/$id'
      path: '/$id'
      fullPath: '/write/$id'
      preLoaderRoute: typeof WriteIdRouteImport
      parentRoute: typeof WriteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TagsRouteChildren {
  TagsTagRoute: typeof TagsTagRoute
}

const TagsRouteChildren: TagsRouteChildren = {
  TagsTagRoute: TagsTagRoute,
}

const TagsRouteWithChildren = TagsRoute._addFileChildren(TagsRouteChildren)

interface WriteRouteChildren {
  WriteIdRoute: typeof WriteIdRoute
}

const WriteRouteChildren: WriteRouteChildren = {
  WriteIdRoute: WriteIdRoute,
}

const WriteRouteWithChildren = WriteRoute._addFileChildren(WriteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntryRoute: EntryRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  CategoriesRoute: CategoriesRoute,
  ConsoleRoute: ConsoleRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  MeRoute: MeRoute,
  MembershipRoute: MembershipRoute,
  MomentsRoute: MomentsRoute,
  ObsidianRoute: ObsidianRoute,
  PhotosRoute: PhotosRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TagsRoute: TagsRouteWithChildren,
  ThemesRoute: ThemesRoute,
  WriteRoute: WriteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  PostsSlugRoute: PostsSlugRoute,
  TopicsTopicRoute: TopicsTopicRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
